[project]
name = "local-ai-rag"
version = "0.1.0"
description = "Local AI RAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "ollama>=0.4.8",
    "qdrant-client[fastembed]>=1.14.2",
    "requests>=2.32.3",
]
